---
- hosts: all 
  become: true
  tasks:
  - name: Install Apache web server
    apt:
      name: apache2
      state: present
  - name: Start Apache
    service:
      name: apache2
      state: started
  - name: enable Apache
    systemd:
      name: apache2
      state: enabled
  - name: virtual host configuration file
    template:
      src: templates/virtualhost.conf.j2
      dest: /etc/apache2/sites-available/example.com.conf
  - name: Enable virtual host
    apache2_module:
      name: ssl
      state: present
      state: enabled
  - name: Restart Apache
    service:
      name: apache2
      state: restarted
